#!/bin/sh
rsync -av ./ businesspay@92.222.85.200:~/panelgestion.businesspay.online --include=public/.htaccess --include=vendor --include=.env --exclude-from=.gitignore --exclude=".*" --exclude="composer.lock"
