dashboard:
    path: /dashboard
    controller: App\Controller\AdminController::index
index:
    path: /
    controller: App\Controller\AdminController::index
login_form:
  path: /login
  controller: App\Controller\SecurityController::showLoginView

dashboard-su:index:
  path: /dashboard/super-user/
  controller: App\Controller\SuperUser\SuperUserAdminController::index




dashboard-su:vgm:index:
  path: /dashboard/super-user/modules/management
  controller: App\Controller\SuperUser\ModulesController::vgmIndex

dashboard-su:vgm:attach:
  path: /dashboard/super-user/modules/management/{module_id}/attach/{admin_id}
  controller: App\Controller\SuperUser\ModulesController::addAdminToVGM



dashboardSuUser:
  path: /dashboard/super-user/gestion-users
  controller: App\Controller\SuperUser\SuperUserAdminController::users

dashboard-su-user:add:
  path: /dashboard/super-user/gestion-users/add
  controller: App\Controller\SuperUser\SuperUserAdminController::insertUser


dashboard-su-user:consignataire:add:
  path: /dashboard/super-user/gestion-consignataire/add
  controller: App\Controller\SuperUser\SuperUserAdminController::addConsignataire

dashboard-su-user:consignataire:index:
  path: /dashboard/super-user/gestion-consignataire
  controller: App\Controller\SuperUser\SuperUserAdminController::consignataireIndex

dashboard-su-user:exportateurs:index:
  path: /dashboard/super-user/gestion-exportateurs
  controller: App\Controller\SuperUser\SuperUserAdminController:exportateursIndex

dashboard-su-user:consignataire:details:
  path: /dashboard/super-user/gestion-consignataire/{id}/detail
  controller: App\Controller\SuperUser\SuperUserAdminController::consignataireDetails
dashboard-su-user:conteneur:index:
  path: /dashboard/super-user/gestion-conteneurs
  controller: App\Controller\SuperUser\SuperUserAdminController::containerIndex

dashboard-su-user:conteneur:add:
  path: /dashboard/super-user/gestion-conteneurs/ajouter
  controller: App\Controller\SuperUser\SuperUserAdminController::insertConteneur

dashboard-su-user:armateur:index:
  path: /dashboard/super-user/gestion-armateurs
  controller: App\Controller\SuperUser\SuperUserAdminController::armateurIndex
dashboard-su-user:cargoTye:index:
  path: /dashboard/super-user/gestion-cargoType
  controller: App\Controller\SuperUser\SuperUserAdminController::cargoType


dashboard-su-user:armateur:add:
  path: /dashboard/super-user/gestion-armateurs/ajouter
  controller: App\Controller\SuperUser\SuperUserAdminController::armateurAdd

dashboard-su-user:country:
  path: /dashboard/super-user/country
  controller: App\Controller\SuperUser\SuperUserAdminController::getcountryList

dashboard-su-user:port:
  path: /dashboard/super-user/port
  controller: App\Controller\SuperUser\SuperUserAdminController::getAllShippingPort


dashboard-su-user:port:add:
  path: /dashboard/super-user/port/add
  controller: App\Controller\SuperUser\SuperUserAdminController::AddShippingPort


dashboard-su-user:delete:
  path: /dashboard/super-user/gestion-users/delete/{id}
  controller: App\Controller\SuperUser\SuperUserAdminController::deleteUser

dashboard-local:vgm:index:
  path: /dashboard/vgm/
  controller: App\Controller\App\vgm\VGMController::index

dashboard-local:vgm:management:index:
  path: /dashboard/vgm/gestion-vgm/
  controller: App\Controller\App\vgm\VGMManagementController::index


dasboard-local:vgm:compagnie:index:
  path:  /dashboard/vgm/gestion-compagnie/
  controller: App\Controller\App\vgm\VGMController::showCompagnie


dashboard-local:vgm:management:searchContainer:

  path: /dashboard/vgm/gestion-vgm/container/search/{QUERY}
  controller: App\Controller\App\vgm\VGMManagementController::searchVGM

dashboard-local:vgm:management:fillInput:
  path: /dashboard/vgm/gestion-vgm/container/fill/{idNum}
  controller: App\Controller\App\vgm\VGMManagementController::fillInput

dashboard-local:vgm:management:createIndex:
  path: /dashboard/vgm/gestion-vgm/create
  controller: App\Controller\App\vgm\CertificatorController::createVGM

dashboard-local:vgm:management:MyVGM:
  path: /dashboard/vgm/gestion-vgm/myVGM
  controller: App\Controller\App\vgm\CertificatorController::getAllCreatedVgm

dashboard-local:vgm:otherAdmin:index:
  path: /dashboard/vgm/gestion-agents/
  controller: App\Controller\App\vgm\OthersAdminController::index

##for vgm validation
dashboard-local:vgm:validaror:index:
  path: /dashboard/vgm/validator/
  controller: App\Controller\App\vgm\ValidatorController::index

dashboard-local:vgm:validaror:vgmList:
  path: /dashboard/vgm/validator/vgm-list
  controller: App\Controller\App\vgm\VGMController::list

dashboard-local:vgm:validaror:vgmDetail:
  path: /dashboard/vgm/validator/vgm/{id}/detail
  controller: App\Controller\App\vgm\VGMController::viewDetailsVgm

dashboard-local:vgm:otherAdmin:create:
  path: /dashboard/vgm/gestion-agents/create
  controller: App\Controller\App\vgm\OthersAdminController::create

dashboard-local:vgm:otherAdmin:certificatorUser:index:
  path: /dashboard/vgm/gestion-certificateurs/
  controller: App\Controller\App\vgm\OthersAdminController::certificatorIndex

dashboard-local:vgm:validatorUser:index:
  path: /dashboard/vgm/gestion-validateurs/
  controller: App\Controller\App\vgm\OthersAdminController::validatorIndex


###for local

###StartE_xportatorPart

dashboard-local:vgm:exportateur:index:
  path: /dashboard/exportator/
  controller: App\Controller\App\base\ClientController::exportatorIndex

dashboard-local:vgm:exportateur:myVgm:
  path: /dashboard/exportator/mes-certificats
  controller: App\Controller\App\base\ClientController::exportatorVgmList

dashboard-local:vgm:exportateur:account:
  path: /dashboard/exportator/account
  controller: App\Controller\App\base\ClientController::exportatorAccount

dashboard-local:vgm:exportateur:buyPoint:
  path: /dashboard/exportator/buy-point
  controller: App\Controller\App\base\ClientController::buyPoint
dashboard-local:vgm:exportateur:payVgm:
  path: /dashboard/exportator/pay/{id}/vgm
  controller: App\Controller\App\base\ClientController::payVgm

dashboard-local:vgm:exportateur:updatePaymentMethod:
  path: /dashboard/exportator/updatePayMethod
  controller: App\Controller\App\base\ClientController::updatePayMethod

dashboard-local:container:index:
  path: /dashboard/vgm/containerList/
  controller: App\Controller\App\vgm\OthersAdminController::validatorIndex

dashboard-local:port:index:
  path: /dashboard/vgm/ports-list/
  controller: App\Controller\App\vgm\OthersAdminController::validatorIndex

dashboard-local:compagnie:index:
  path: /dashboard/vgm/compagnie-list/
  controller: App\Controller\App\vgm\OthersAdminController::validatorIndex


dashboard-local:login:
  path: /dashboard/local-admin/login
  controller: App\Controller\local\LocalAdminController::showLoginForm


dashboard-local:index:
  path: /dashboard/local-admin
  controller: App\Controller\local\LocalAdminController::index


dashboard-local:vgm:controller:index:
  path: /dashboard/vgm/controller/index
  controller: App\Controller\App\vgm\OthersAdminController::controllerIndex
dashboard-local:container:searchContainer:
    path: /dashboard/container
    controller: App\Controller\App\vgm\OthersAdminController::controllerIndex

dashboard-local:vgm:validateAndControl:
  path: /dashboard/vgm/{id}/validate-contole
  controller: App\Controller\App\vgm\OthersAdminController::validateControle

logout:
  path: /logout



