dashboard:
    path: /dashboard
    controller: App\Controller\AdminController::index
index:
    path: /
    controller: App\Controller\AdminController::index
login_form:
  path: /login
  controller: App\Controller\SecurityController::showLoginView

dashboard-su:index:
  path: /dashboard/super-user/
  controller: App\Controller\SuperUser\SuperUserAdminController::index




dashboard-su:vgm:index:
  path: /dashboard/super-user/modules/management
  controller: App\Controller\SuperUser\ModulesController::vgmIndex

dashboard-su:vgm:attach:
  path: /dashboard/super-user/modules/management/{module_id}/attach/{admin_id}
  controller: App\Controller\SuperUser\ModulesController::addAdminToVGM



dashboardSuUser:
  path: /dashboard/super-user/gestion-users
  controller: App\Controller\SuperUser\SuperUserAdminController::users

dashboard-su-user:add:
  path: /dashboard/super-user/gestion-users/add
  controller: App\Controller\SuperUser\SuperUserAdminController::insertUser

dashboard-su-user:cargoType:
  path: /dashboard/super-user/gestion-cargo
  controller: App\Controller\SuperUser\SuperUserAdminController::indexCargoType

dashboard-su-user:cargoTtype:add:
  path: /dashboard/super-user/gestion-cargo
  controller: App\Controller\SuperUser\SuperUserAdminController::addCargoType

dashboard-su-user:consignataire:add:
  path: /dashboard/super-user/gestion-consignataire/add
  controller: App\Controller\SuperUser\SuperUserAdminController::addConsignataire

dashboard-su-user:consignataire:index:
  path: /dashboard/super-user/gestion-consignataire
  controller: App\Controller\SuperUser\SuperUserAdminController::consignataireIndex
dashboard-su-user:conteneur:index:
  path: /dashboard/super-user/gestion-conteneurs
  controller: App\Controller\SuperUser\SuperUserAdminController::containerIndex

dashboard-su-user:conteneur:add:
  path: /dashboard/super-user/gestion-conteneurs/ajouter
  controller: App\Controller\SuperUser\SuperUserAdminController::insertConteneur

dashboard-su-user:armateur:index:
  path: /dashboard/super-user/gestion-armateurs
  controller: App\Controller\SuperUser\SuperUserAdminController::armateurIndex


dashboard-su-user:armateur:add:
  path: /dashboard/super-user/gestion-armateurs/ajouter
  controller: App\Controller\SuperUser\SuperUserAdminController::armateurAdd

dashboard-su-user:country:
  path: /dashboard/super-user/country
  controller: App\Controller\SuperUser\SuperUserAdminController::getcountryList

dashboard-su-user:port:
  path: /dashboard/super-user/port
  controller: App\Controller\SuperUser\SuperUserAdminController::getAllShippingPort


dashboard-su-user:port:add:
  path: /dashboard/super-user/port/add
  controller: App\Controller\SuperUser\SuperUserAdminController::AddShippingPort


dashboard-su-user:delete:
  path: /dashboard/super-user/gestion-users/delete/{id}
  controller: App\Controller\SuperUser\SuperUserAdminController::deleteUser

dashboard-local:vgm:index:
  path: /dashboard/vgm/
  controller: App\Controller\App\vgm\VGMController::index

dashboard-local:vgm:management:index:
  path: /dashboard/vgm/gestion-vgm/
  controller: App\Controller\App\vgm\VGMManagementController::index


dasboard-local:vgm:compagnie:index:
  path:  /dashboard/vgm/gestion-compagnie/
  controller: App\Controller\App\vgm\VGMController::showCompagnie


dashboard-local:vgm:management:createIndex:
  path: /dashboard/vgm/gestion-vgm/create
  controller: App\Controller\App\vgm\VGMManagementController::createVGM

dashboard-local:vgm:otherAdmin:index:
  path: /dashboard/vgm/gestion-agents/
  controller: App\Controller\App\vgm\OthersAdminController::index

dashboard-local:vgm:otherAdmin:create:
  path: /dashboard/vgm/gestion-agents/create
  controller: App\Controller\App\vgm\OthersAdminController::create

dashboard-local:vgm:otherAdmin:certificatorUser:index:
  path: /dashboard/vgm/gestion-certificateurs/
  controller: App\Controller\App\vgm\OthersAdminController::certificatorIndex

dashboard-local:vgm:otherAdmin:validatorUser:index:
  path: /dashboard/vgm/gestion-validateurs/
  controller: App\Controller\App\vgm\OthersAdminController::validatorIndex



dashboard-local:login:
  path: /dashboard/local-admin/login
  controller: App\Controller\local\LocalAdminController::showLoginForm


dashboard-local:index:
  path: /dashboard/local-admin
  controller: App\Controller\local\LocalAdminController::index

logout:
  path: /logout



